Gabriel db models
DevWorkflow12/ProyectoPF pull request #8
Opened 2023-09-27 22:45 UTC by Gabriel-Piumetto

se crea el model de Empresas, NivelJerarquico, Rubros, Work-flows...se crea el json con la info de rubro

2023-09-27 22:59 UTC, Angelaguado96 approved these changes
ok

2023-09-27 23:02 UTC, Chris-tAt approved these changes

2023-09-27 23:03 UTC, angel-lira approved these changes
👍

2023-09-27 23:08 UTC, angel-lira requested changes
❌

2023-09-28 00:16 UTC, angel-lira approved these changes
👍👍

2023-09-28 00:34 UTC, merged